doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        
        # Configuration pour SQLite en dev
        options:
            # Pour SQLite
            sqlite: 
                user: null
                password: null
                
        # Types mapp√©s pour PostgreSQL
        mapping_types:
            enum: string
            json: json

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'